<?php

namespace ArticleBundle\Repository;

/**
 * ArticleLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleLikeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLike()
    {
        return $this->findBy(array(), array('updatedAt' => 'DESC'));
    }
}
